name: Jekyll site CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Downgraded to v1 till this it works with v2
        # Follow up: https://github.com/actions/setup-node/issues/224
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
